// Code generated by protoc-gen-go. DO NOT EDIT.
// source: metaServer.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Target struct {
	DestAddr             string   `protobuf:"bytes,1,opt,name=destAddr,proto3" json:"destAddr,omitempty"`
	DestDir              string   `protobuf:"bytes,2,opt,name=destDir,proto3" json:"destDir,omitempty"`
	DestId               string   `protobuf:"bytes,3,opt,name=destId,proto3" json:"destId,omitempty"`
	SgId                 int32    `protobuf:"varint,4,opt,name=sgId,proto3" json:"sgId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Target) Reset()         { *m = Target{} }
func (m *Target) String() string { return proto.CompactTextString(m) }
func (*Target) ProtoMessage()    {}
func (*Target) Descriptor() ([]byte, []int) {
	return fileDescriptor_127d24f87da8287f, []int{0}
}

func (m *Target) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Target.Unmarshal(m, b)
}
func (m *Target) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Target.Marshal(b, m, deterministic)
}
func (m *Target) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Target.Merge(m, src)
}
func (m *Target) XXX_Size() int {
	return xxx_messageInfo_Target.Size(m)
}
func (m *Target) XXX_DiscardUnknown() {
	xxx_messageInfo_Target.DiscardUnknown(m)
}

var xxx_messageInfo_Target proto.InternalMessageInfo

func (m *Target) GetDestAddr() string {
	if m != nil {
		return m.DestAddr
	}
	return ""
}

func (m *Target) GetDestDir() string {
	if m != nil {
		return m.DestDir
	}
	return ""
}

func (m *Target) GetDestId() string {
	if m != nil {
		return m.DestId
	}
	return ""
}

func (m *Target) GetSgId() int32 {
	if m != nil {
		return m.SgId
	}
	return 0
}

type AskPutRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Size                 int64    `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Object               string   `protobuf:"bytes,3,opt,name=object,proto3" json:"object,omitempty"`
	ObjectHash           string   `protobuf:"bytes,4,opt,name=objectHash,proto3" json:"objectHash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AskPutRequest) Reset()         { *m = AskPutRequest{} }
func (m *AskPutRequest) String() string { return proto.CompactTextString(m) }
func (*AskPutRequest) ProtoMessage()    {}
func (*AskPutRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_127d24f87da8287f, []int{1}
}

func (m *AskPutRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AskPutRequest.Unmarshal(m, b)
}
func (m *AskPutRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AskPutRequest.Marshal(b, m, deterministic)
}
func (m *AskPutRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AskPutRequest.Merge(m, src)
}
func (m *AskPutRequest) XXX_Size() int {
	return xxx_messageInfo_AskPutRequest.Size(m)
}
func (m *AskPutRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AskPutRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AskPutRequest proto.InternalMessageInfo

func (m *AskPutRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AskPutRequest) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *AskPutRequest) GetObject() string {
	if m != nil {
		return m.Object
	}
	return ""
}

func (m *AskPutRequest) GetObjectHash() string {
	if m != nil {
		return m.ObjectHash
	}
	return ""
}

type AskPutResponse struct {
	Status               int32     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Targets              []*Target `protobuf:"bytes,2,rep,name=targets,proto3" json:"targets,omitempty"`
	Msg                  string    `protobuf:"bytes,4,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *AskPutResponse) Reset()         { *m = AskPutResponse{} }
func (m *AskPutResponse) String() string { return proto.CompactTextString(m) }
func (*AskPutResponse) ProtoMessage()    {}
func (*AskPutResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_127d24f87da8287f, []int{2}
}

func (m *AskPutResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AskPutResponse.Unmarshal(m, b)
}
func (m *AskPutResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AskPutResponse.Marshal(b, m, deterministic)
}
func (m *AskPutResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AskPutResponse.Merge(m, src)
}
func (m *AskPutResponse) XXX_Size() int {
	return xxx_messageInfo_AskPutResponse.Size(m)
}
func (m *AskPutResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AskPutResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AskPutResponse proto.InternalMessageInfo

func (m *AskPutResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *AskPutResponse) GetTargets() []*Target {
	if m != nil {
		return m.Targets
	}
	return nil
}

func (m *AskPutResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type AskGetRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AskGetRequest) Reset()         { *m = AskGetRequest{} }
func (m *AskGetRequest) String() string { return proto.CompactTextString(m) }
func (*AskGetRequest) ProtoMessage()    {}
func (*AskGetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_127d24f87da8287f, []int{3}
}

func (m *AskGetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AskGetRequest.Unmarshal(m, b)
}
func (m *AskGetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AskGetRequest.Marshal(b, m, deterministic)
}
func (m *AskGetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AskGetRequest.Merge(m, src)
}
func (m *AskGetRequest) XXX_Size() int {
	return xxx_messageInfo_AskGetRequest.Size(m)
}
func (m *AskGetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AskGetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AskGetRequest proto.InternalMessageInfo

func (m *AskGetRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type AskGetResponse struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Target               *Target  `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Msg                  string   `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AskGetResponse) Reset()         { *m = AskGetResponse{} }
func (m *AskGetResponse) String() string { return proto.CompactTextString(m) }
func (*AskGetResponse) ProtoMessage()    {}
func (*AskGetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_127d24f87da8287f, []int{4}
}

func (m *AskGetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AskGetResponse.Unmarshal(m, b)
}
func (m *AskGetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AskGetResponse.Marshal(b, m, deterministic)
}
func (m *AskGetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AskGetResponse.Merge(m, src)
}
func (m *AskGetResponse) XXX_Size() int {
	return xxx_messageInfo_AskGetResponse.Size(m)
}
func (m *AskGetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AskGetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AskGetResponse proto.InternalMessageInfo

func (m *AskGetResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *AskGetResponse) GetTarget() *Target {
	if m != nil {
		return m.Target
	}
	return nil
}

func (m *AskGetResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*Target)(nil), "pb.Target")
	proto.RegisterType((*AskPutRequest)(nil), "pb.AskPutRequest")
	proto.RegisterType((*AskPutResponse)(nil), "pb.AskPutResponse")
	proto.RegisterType((*AskGetRequest)(nil), "pb.AskGetRequest")
	proto.RegisterType((*AskGetResponse)(nil), "pb.AskGetResponse")
}

func init() { proto.RegisterFile("metaServer.proto", fileDescriptor_127d24f87da8287f) }

var fileDescriptor_127d24f87da8287f = []byte{
	// 323 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0x41, 0x4f, 0xf2, 0x40,
	0x10, 0x05, 0x0a, 0xe5, 0x63, 0xc8, 0x67, 0x70, 0x0e, 0xa6, 0xe1, 0x60, 0xc8, 0xea, 0x81, 0x53,
	0x13, 0xf1, 0xe8, 0x09, 0x63, 0x82, 0x1c, 0x4c, 0xcc, 0xea, 0xc9, 0x83, 0xb1, 0xa5, 0x13, 0x04,
	0x03, 0xad, 0x9d, 0xc5, 0x83, 0xbf, 0xde, 0xec, 0xec, 0x16, 0xca, 0x45, 0x6f, 0xef, 0xed, 0xec,
	0xeb, 0x7b, 0x6f, 0xba, 0x30, 0xd8, 0x90, 0x49, 0x9e, 0xa8, 0xfc, 0xa2, 0x32, 0x2e, 0xca, 0xdc,
	0xe4, 0xd8, 0x2a, 0x52, 0xb5, 0x86, 0xf0, 0x39, 0x29, 0x97, 0x64, 0x70, 0x08, 0xff, 0x32, 0x62,
	0x33, 0xcd, 0xb2, 0x32, 0x6a, 0x8e, 0x9a, 0xe3, 0x9e, 0xde, 0x73, 0x8c, 0xa0, 0x6b, 0xf1, 0xdd,
	0xaa, 0x8c, 0x5a, 0x32, 0xaa, 0x28, 0x9e, 0x41, 0x68, 0xe1, 0x3c, 0x8b, 0x02, 0x19, 0x78, 0x86,
	0x08, 0x6d, 0x5e, 0xce, 0xb3, 0xa8, 0x3d, 0x6a, 0x8e, 0x3b, 0x5a, 0xb0, 0xca, 0xe1, 0xff, 0x94,
	0x3f, 0x1e, 0x77, 0x46, 0xd3, 0xe7, 0x8e, 0xd8, 0xd8, 0x4b, 0xdb, 0x64, 0x43, 0xde, 0x4e, 0xb0,
	0x08, 0x57, 0xdf, 0x24, 0x3e, 0x81, 0x16, 0x6c, 0x4d, 0xf2, 0x74, 0x4d, 0x0b, 0x53, 0x99, 0x38,
	0x86, 0xe7, 0x00, 0x0e, 0xdd, 0x27, 0xfc, 0x2e, 0x56, 0x3d, 0x5d, 0x3b, 0x51, 0x6f, 0x70, 0x52,
	0x19, 0x72, 0x91, 0x6f, 0x59, 0xbe, 0xc4, 0x26, 0x31, 0x3b, 0x16, 0xcf, 0x8e, 0xf6, 0x0c, 0x2f,
	0xa1, 0x6b, 0x64, 0x0d, 0x1c, 0xb5, 0x46, 0xc1, 0xb8, 0x3f, 0x81, 0xb8, 0x48, 0x63, 0xb7, 0x19,
	0x5d, 0x8d, 0x70, 0x00, 0xc1, 0x86, 0x97, 0xde, 0xc8, 0x42, 0x75, 0x21, 0x95, 0x66, 0xf4, 0x5b,
	0x25, 0xf5, 0x2a, 0x31, 0xe4, 0xd2, 0x1f, 0x31, 0x14, 0x84, 0xce, 0x4b, 0xea, 0x1f, 0xa7, 0xf0,
	0x93, 0x2a, 0x44, 0xb0, 0x0f, 0x31, 0x61, 0xe8, 0x3f, 0xf8, 0x7f, 0xbb, 0x5a, 0x10, 0x5e, 0x41,
	0xe8, 0x5a, 0xe3, 0xa9, 0x95, 0x1f, 0xad, 0x7c, 0x88, 0xf5, 0x23, 0x97, 0x46, 0x35, 0xbc, 0x64,
	0x46, 0x07, 0xc9, 0xa1, 0xd2, 0x5e, 0x52, 0x2b, 0xa0, 0x1a, 0xb7, 0xe1, 0x4b, 0x3b, 0xbe, 0x29,
	0xd2, 0x34, 0x94, 0xb7, 0x74, 0xfd, 0x13, 0x00, 0x00, 0xff, 0xff, 0x2e, 0x8e, 0x8d, 0xe8, 0x5f,
	0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MetaServiceClient is the client API for MetaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MetaServiceClient interface {
	AskPut(ctx context.Context, in *AskPutRequest, opts ...grpc.CallOption) (*AskPutResponse, error)
	AskGet(ctx context.Context, in *AskGetRequest, opts ...grpc.CallOption) (*AskGetResponse, error)
}

type metaServiceClient struct {
	cc *grpc.ClientConn
}

func NewMetaServiceClient(cc *grpc.ClientConn) MetaServiceClient {
	return &metaServiceClient{cc}
}

func (c *metaServiceClient) AskPut(ctx context.Context, in *AskPutRequest, opts ...grpc.CallOption) (*AskPutResponse, error) {
	out := new(AskPutResponse)
	err := c.cc.Invoke(ctx, "/pb.MetaService/AskPut", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metaServiceClient) AskGet(ctx context.Context, in *AskGetRequest, opts ...grpc.CallOption) (*AskGetResponse, error) {
	out := new(AskGetResponse)
	err := c.cc.Invoke(ctx, "/pb.MetaService/AskGet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MetaServiceServer is the server API for MetaService service.
type MetaServiceServer interface {
	AskPut(context.Context, *AskPutRequest) (*AskPutResponse, error)
	AskGet(context.Context, *AskGetRequest) (*AskGetResponse, error)
}

// UnimplementedMetaServiceServer can be embedded to have forward compatible implementations.
type UnimplementedMetaServiceServer struct {
}

func (*UnimplementedMetaServiceServer) AskPut(ctx context.Context, req *AskPutRequest) (*AskPutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AskPut not implemented")
}
func (*UnimplementedMetaServiceServer) AskGet(ctx context.Context, req *AskGetRequest) (*AskGetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AskGet not implemented")
}

func RegisterMetaServiceServer(s *grpc.Server, srv MetaServiceServer) {
	s.RegisterService(&_MetaService_serviceDesc, srv)
}

func _MetaService_AskPut_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AskPutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetaServiceServer).AskPut(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.MetaService/AskPut",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetaServiceServer).AskPut(ctx, req.(*AskPutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetaService_AskGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AskGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetaServiceServer).AskGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.MetaService/AskGet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetaServiceServer).AskGet(ctx, req.(*AskGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MetaService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.MetaService",
	HandlerType: (*MetaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AskPut",
			Handler:    _MetaService_AskPut_Handler,
		},
		{
			MethodName: "AskGet",
			Handler:    _MetaService_AskGet_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "metaServer.proto",
}
