// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.21.0
// 	protoc        v3.6.1
// source: metaServer.proto

package pb

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Target struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DestAddr string `protobuf:"bytes,1,opt,name=destAddr,proto3" json:"destAddr,omitempty"`
	DestDir  string `protobuf:"bytes,2,opt,name=destDir,proto3" json:"destDir,omitempty"`
	DestId   string `protobuf:"bytes,3,opt,name=destId,proto3" json:"destId,omitempty"`
	SgId     int32  `protobuf:"varint,4,opt,name=sgId,proto3" json:"sgId,omitempty"`
}

func (x *Target) Reset() {
	*x = Target{}
	if protoimpl.UnsafeEnabled {
		mi := &file_metaServer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Target) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Target) ProtoMessage() {}

func (x *Target) ProtoReflect() protoreflect.Message {
	mi := &file_metaServer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Target.ProtoReflect.Descriptor instead.
func (*Target) Descriptor() ([]byte, []int) {
	return file_metaServer_proto_rawDescGZIP(), []int{0}
}

func (x *Target) GetDestAddr() string {
	if x != nil {
		return x.DestAddr
	}
	return ""
}

func (x *Target) GetDestDir() string {
	if x != nil {
		return x.DestDir
	}
	return ""
}

func (x *Target) GetDestId() string {
	if x != nil {
		return x.DestId
	}
	return ""
}

func (x *Target) GetSgId() int32 {
	if x != nil {
		return x.SgId
	}
	return 0
}

type AskPutRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name       string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Size       int64  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Object     string `protobuf:"bytes,3,opt,name=object,proto3" json:"object,omitempty"`
	ObjectHash string `protobuf:"bytes,4,opt,name=objectHash,proto3" json:"objectHash,omitempty"`
}

func (x *AskPutRequest) Reset() {
	*x = AskPutRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_metaServer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AskPutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AskPutRequest) ProtoMessage() {}

func (x *AskPutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metaServer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AskPutRequest.ProtoReflect.Descriptor instead.
func (*AskPutRequest) Descriptor() ([]byte, []int) {
	return file_metaServer_proto_rawDescGZIP(), []int{1}
}

func (x *AskPutRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AskPutRequest) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *AskPutRequest) GetObject() string {
	if x != nil {
		return x.Object
	}
	return ""
}

func (x *AskPutRequest) GetObjectHash() string {
	if x != nil {
		return x.ObjectHash
	}
	return ""
}

type AskPutResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  int32     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Targets []*Target `protobuf:"bytes,2,rep,name=targets,proto3" json:"targets,omitempty"`
	Msg     string    `protobuf:"bytes,4,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *AskPutResponse) Reset() {
	*x = AskPutResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_metaServer_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AskPutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AskPutResponse) ProtoMessage() {}

func (x *AskPutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metaServer_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AskPutResponse.ProtoReflect.Descriptor instead.
func (*AskPutResponse) Descriptor() ([]byte, []int) {
	return file_metaServer_proto_rawDescGZIP(), []int{2}
}

func (x *AskPutResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *AskPutResponse) GetTargets() []*Target {
	if x != nil {
		return x.Targets
	}
	return nil
}

func (x *AskPutResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type AskGetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *AskGetRequest) Reset() {
	*x = AskGetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_metaServer_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AskGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AskGetRequest) ProtoMessage() {}

func (x *AskGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metaServer_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AskGetRequest.ProtoReflect.Descriptor instead.
func (*AskGetRequest) Descriptor() ([]byte, []int) {
	return file_metaServer_proto_rawDescGZIP(), []int{3}
}

func (x *AskGetRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type AskGetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int32   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Target *Target `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Msg    string  `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *AskGetResponse) Reset() {
	*x = AskGetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_metaServer_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AskGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AskGetResponse) ProtoMessage() {}

func (x *AskGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metaServer_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AskGetResponse.ProtoReflect.Descriptor instead.
func (*AskGetResponse) Descriptor() ([]byte, []int) {
	return file_metaServer_proto_rawDescGZIP(), []int{4}
}

func (x *AskGetResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *AskGetResponse) GetTarget() *Target {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *AskGetResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_metaServer_proto protoreflect.FileDescriptor

var file_metaServer_proto_rawDesc = []byte{
	0x0a, 0x10, 0x6d, 0x65, 0x74, 0x61, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x6a, 0x0a, 0x06, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74,
	0x12, 0x1a, 0x0a, 0x08, 0x64, 0x65, 0x73, 0x74, 0x41, 0x64, 0x64, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x64, 0x65, 0x73, 0x74, 0x41, 0x64, 0x64, 0x72, 0x12, 0x18, 0x0a, 0x07,
	0x64, 0x65, 0x73, 0x74, 0x44, 0x69, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x64,
	0x65, 0x73, 0x74, 0x44, 0x69, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x65, 0x73, 0x74, 0x49, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x65, 0x73, 0x74, 0x49, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x73, 0x67, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x73, 0x67,
	0x49, 0x64, 0x22, 0x6f, 0x0a, 0x0d, 0x41, 0x73, 0x6b, 0x50, 0x75, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6f,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x62, 0x6a,
	0x65, 0x63, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x48, 0x61, 0x73,
	0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x48,
	0x61, 0x73, 0x68, 0x22, 0x60, 0x0a, 0x0e, 0x41, 0x73, 0x6b, 0x50, 0x75, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x24, 0x0a,
	0x07, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a,
	0x2e, 0x70, 0x62, 0x2e, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x52, 0x07, 0x74, 0x61, 0x72, 0x67,
	0x65, 0x74, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x23, 0x0a, 0x0d, 0x41, 0x73, 0x6b, 0x47, 0x65, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x5e, 0x0a, 0x0e, 0x41, 0x73,
	0x6b, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x22, 0x0a, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x70, 0x62, 0x2e, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74,
	0x52, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x32, 0x73, 0x0a, 0x0b, 0x4d, 0x65,
	0x74, 0x61, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x31, 0x0a, 0x06, 0x41, 0x73, 0x6b,
	0x50, 0x75, 0x74, 0x12, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x73, 0x6b, 0x50, 0x75, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x73, 0x6b, 0x50,
	0x75, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x31, 0x0a, 0x06,
	0x41, 0x73, 0x6b, 0x47, 0x65, 0x74, 0x12, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x73, 0x6b, 0x47,
	0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x41,
	0x73, 0x6b, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42,
	0x06, 0x5a, 0x04, 0x2e, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_metaServer_proto_rawDescOnce sync.Once
	file_metaServer_proto_rawDescData = file_metaServer_proto_rawDesc
)

func file_metaServer_proto_rawDescGZIP() []byte {
	file_metaServer_proto_rawDescOnce.Do(func() {
		file_metaServer_proto_rawDescData = protoimpl.X.CompressGZIP(file_metaServer_proto_rawDescData)
	})
	return file_metaServer_proto_rawDescData
}

var file_metaServer_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_metaServer_proto_goTypes = []interface{}{
	(*Target)(nil),         // 0: pb.Target
	(*AskPutRequest)(nil),  // 1: pb.AskPutRequest
	(*AskPutResponse)(nil), // 2: pb.AskPutResponse
	(*AskGetRequest)(nil),  // 3: pb.AskGetRequest
	(*AskGetResponse)(nil), // 4: pb.AskGetResponse
}
var file_metaServer_proto_depIdxs = []int32{
	0, // 0: pb.AskPutResponse.targets:type_name -> pb.Target
	0, // 1: pb.AskGetResponse.target:type_name -> pb.Target
	1, // 2: pb.MetaService.AskPut:input_type -> pb.AskPutRequest
	3, // 3: pb.MetaService.AskGet:input_type -> pb.AskGetRequest
	2, // 4: pb.MetaService.AskPut:output_type -> pb.AskPutResponse
	4, // 5: pb.MetaService.AskGet:output_type -> pb.AskGetResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_metaServer_proto_init() }
func file_metaServer_proto_init() {
	if File_metaServer_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_metaServer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Target); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_metaServer_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AskPutRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_metaServer_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AskPutResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_metaServer_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AskGetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_metaServer_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AskGetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_metaServer_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_metaServer_proto_goTypes,
		DependencyIndexes: file_metaServer_proto_depIdxs,
		MessageInfos:      file_metaServer_proto_msgTypes,
	}.Build()
	File_metaServer_proto = out.File
	file_metaServer_proto_rawDesc = nil
	file_metaServer_proto_goTypes = nil
	file_metaServer_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// MetaServiceClient is the client API for MetaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MetaServiceClient interface {
	AskPut(ctx context.Context, in *AskPutRequest, opts ...grpc.CallOption) (*AskPutResponse, error)
	AskGet(ctx context.Context, in *AskGetRequest, opts ...grpc.CallOption) (*AskGetResponse, error)
}

type metaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMetaServiceClient(cc grpc.ClientConnInterface) MetaServiceClient {
	return &metaServiceClient{cc}
}

func (c *metaServiceClient) AskPut(ctx context.Context, in *AskPutRequest, opts ...grpc.CallOption) (*AskPutResponse, error) {
	out := new(AskPutResponse)
	err := c.cc.Invoke(ctx, "/pb.MetaService/AskPut", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metaServiceClient) AskGet(ctx context.Context, in *AskGetRequest, opts ...grpc.CallOption) (*AskGetResponse, error) {
	out := new(AskGetResponse)
	err := c.cc.Invoke(ctx, "/pb.MetaService/AskGet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MetaServiceServer is the server API for MetaService service.
type MetaServiceServer interface {
	AskPut(context.Context, *AskPutRequest) (*AskPutResponse, error)
	AskGet(context.Context, *AskGetRequest) (*AskGetResponse, error)
}

// UnimplementedMetaServiceServer can be embedded to have forward compatible implementations.
type UnimplementedMetaServiceServer struct {
}

func (*UnimplementedMetaServiceServer) AskPut(context.Context, *AskPutRequest) (*AskPutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AskPut not implemented")
}
func (*UnimplementedMetaServiceServer) AskGet(context.Context, *AskGetRequest) (*AskGetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AskGet not implemented")
}

func RegisterMetaServiceServer(s *grpc.Server, srv MetaServiceServer) {
	s.RegisterService(&_MetaService_serviceDesc, srv)
}

func _MetaService_AskPut_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AskPutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetaServiceServer).AskPut(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.MetaService/AskPut",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetaServiceServer).AskPut(ctx, req.(*AskPutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetaService_AskGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AskGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetaServiceServer).AskGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.MetaService/AskGet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetaServiceServer).AskGet(ctx, req.(*AskGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MetaService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.MetaService",
	HandlerType: (*MetaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AskPut",
			Handler:    _MetaService_AskPut_Handler,
		},
		{
			MethodName: "AskGet",
			Handler:    _MetaService_AskGet_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "metaServer.proto",
}
